### PR TITLE
Build Docker image

### PR DESCRIPTION
**Pull request by frafra**
This is a simple CI system, which tries to build a Docker image and push it to GitHub registry.

I am not able to build the image at the moment due to a build error (PR #20 should be merged first).
`GSS` is not a valid name for an image, as it is uppercase, so I had to rename my fork to `gss` (lowercase). This repository should do the same before merging this PR.

### CODE REVIEW

**Comment by moovida** [comment]
@frafra , you mean that the repo needs to be renamed to "gss" for the action to work?

**Comment by frafra** [comment]
The image has been build correctly: https://github.com/frafra/GSS/pkgs/container/gss
Images are private by default, but such policy can be changed from the web interface `[...]/packages/container/gss/settings` -> `Danger zone`.

**Comment by moovida** [comment]
The link of the page you describe does not exist. And if I look into my settings, in the danger zone I do not see a section about images:

image

**Comment by frafra** [comment]
I guess it can be set only after something has been published.

**Comment by moovida** [comment]
ok, let's have a try then.

**Comment by frafra** [comment]
The image is there, but it should be made visible for everybody.

**Comment by moovida** [comment]
I am struggeling to find the right spot. Following more or less your url reconstruction I went to:

https://github.com/geopaparazzi/GSS/pkgs/container/gss/settings

which then resolves into: 

https://github.com/geopaparazzi/GSS/pkgs/container/gss/17681143

which is visible only when logged. 

The only settings I see are the ones of the repo, which is where I do not see anything about visibility of packages.

Any clue?

**Comment by frafra** [comment]
The URL is wrong, sorry. You should look at https://github.com/geopaparazzi/GSS/pkgs/container/gss and have a "Settings" link on the right bar.

**Comment by moovida** [comment]
Ahhh, finally found, it is "Package visibility". Didn' see that before. 
Now I am just struggeling with the fact that I am not allowed to change it. That is really strange, being the admin :-D

**Comment by frafra** [comment]
It works, thank you :-)

**Comment by moovida** [comment]
Super, thank you :-)

**Pull request merged**
